/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package google.newpackage;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aa
 */
public class gooooog extends javax.swing.JFrame {

    /**
     * Creates new form gooooog
     */
    public gooooog() {
        initComponents();
    }
int z1=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser3 = new javax.swing.JFileChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        jFileChooser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton2.setText("IMAGE");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 170, 30));

        jButton13.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton13.setText("VERIFY");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 180, 30));

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("ENTER YOUR  SEARCH RESULT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 60));

        jButton3.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton3.setText("GOOGLE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, 30));

        jLabel3.setFont(new java.awt.Font("Vijaya", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 140, 50));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("YOUR SCORE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 260, 33));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 255, 0));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 40));

        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton1.setText("SCORE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/google/newpackage/google_wallpaper_by_seudesigns-d5evurs.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        jTabbedPane2.addTab("ROUND 1", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        jButton7.setText("Confirm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ENTER PASSWORD");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("LOG IN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 14));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 204, 0));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.setEnabled(false);
        jTextField2.setOpaque(false);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 490, 30));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpinner1.setEnabled(false);
        jSpinner1.setOpaque(false);
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 70, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("WEBSITE");
        jButton5.setEnabled(false);
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Google Search");
        jButton4.setBorderPainted(false);
        jButton4.setEnabled(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/google/newpackage/google-wallpaper-dark-by-zeke-ulrich_1.jpg"))); // NOI18N
        jLabel5.setEnabled(false);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 750));

        jTabbedPane2.addTab("ROUND 2", jPanel2);

        jLabel6.setEnabled(false);
        jTabbedPane2.addTab("WEBSITE", jLabel6);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 880, 30));

        jButton12.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jButton12.setText("REFRESH");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 30));

        jLabel15.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 120, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("LOG IN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 14));

        jButton10.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton10.setText("VERIFY");
        jButton10.setEnabled(false);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 180, 30));

        jButton11.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton11.setText("HINT");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 130, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("ENTER PASSWORD");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel3.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        jButton9.setText("Confirm");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p" }));
        jComboBox1.setEnabled(false);
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 60, 30));

        jButton8.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton8.setText("IMAGE");
        jButton8.setEnabled(false);
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, 30));

        jButton6.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jButton6.setText("GOOGLE");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, 30));

        jLabel10.setEnabled(false);
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 580, 380));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/google/newpackage/gog1.PNG"))); // NOI18N
        jLabel7.setEnabled(false);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 598));

        jTabbedPane2.addTab("ROUND 3", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        jTabbedPane2.addTab("UPLOAD IMAGE", jPanel5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int retVal = jFileChooser3.showOpenDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser3.getSelectedFile();
            jLabel13.setIcon(new ImageIcon(""+f));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            String url="https://www.google.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=Integer.parseInt(jTextField1.getText());
        int z=2;

        System.out.println(i);
        if(i >19000 && i<=20000)
        {
            jLabel3.setText(String.valueOf(100+z));
            System.out.println(i);  }
        if(i >18000 && i<=19000)
        {
            jLabel3.setText(String.valueOf(100+z*2));
        }
        if(i >17000 && i<=18000)
        {
            jLabel3.setText(String.valueOf(100+z*3));
        }
        if(i >16000 && i<=17000)
        {
            jLabel3.setText(String.valueOf(100+z*4));
        }
        if(i >15000 && i<=16000)
        {
            jLabel3.setText(String.valueOf(100+z*5));
        }
        if(i >14000 && i<=15000)
        {
            jLabel3.setText(String.valueOf(100+z*6));
        }
        if(i >13000 && i<=14000)
        {
            jLabel3.setText(String.valueOf(100+z*7));
        }
        if(i >12000 && i<=13000)
        {
            jLabel3.setText(String.valueOf(100+z*8));
        }
        if(i >11000 && i<=12000)
        {
            jLabel3.setText(String.valueOf(100+z*10));
        }
        if(i >10000 && i<=11000)
        {
            jLabel3.setText(String.valueOf(100+z*11));
        }
        if(i >9000 && i<=10000)
        {
            jLabel3.setText(String.valueOf(100+z*12));
        }
        if(i >8000 && i<=9000)
        {
            jLabel3.setText(String.valueOf(100+z*13));
        }
        if(i >7000 && i<=8000)
        {
            jLabel3.setText(String.valueOf(100+z*14));
        }

        if(i >6000 && i<=7000)
        {
            jLabel3.setText(String.valueOf(100+z*16));
        }
        if(i >5000 && i<=6000)
        {
            jLabel3.setText(String.valueOf(100+z*18));
        }
        if(i >4000 && i<=5000)
        {
            jLabel3.setText(String.valueOf(100+z*19));
        }
        if(i >3000 && i<=4000)
        {
            jLabel3.setText(String.valueOf(100+z*21));
        }
        if(i >2000 && i<=3000)
        {
            jLabel3.setText(String.valueOf(100+z*22));
        }
        if(i >1000 && i<=2000)
        {
            jLabel3.setText(String.valueOf(100+z*23));
        }

        if(i >500 && i<=1000)
        {
            jLabel3.setText(String.valueOf(100+z*24));
        }
        if(i >0 && i<=500)
        {
            jLabel3.setText(String.valueOf(100+z*25));
        }
        if(i >20000 && i<=21000)
        {
            jLabel3.setText(String.valueOf(100-z));
        }
        if(i >21000 && i<=22000)
        {
            jLabel3.setText(String.valueOf(100-z*2));
        }
        if(i >22000 && i<=23000)
        {
            jLabel3.setText(String.valueOf(100-z*3));
        }
        if(i >23000 && i<=24000)
        {
            jLabel3.setText(String.valueOf(100-z*4));
        }
        if(i >24000 && i<=25000)
        {
            jLabel3.setText(String.valueOf(100-z*5));
        }
        if(i >25000 && i<=26000)
        {
            jLabel3.setText(String.valueOf(100-z*6));
        }
        if(i >26000 && i<=27000)
        {
            jLabel3.setText(String.valueOf(100-z*7));
        }
        if(i >27000 && i<=28000)
        {
            jLabel3.setText(String.valueOf(100-z*8));
        }
        if(i >28000 && i<=29000)
        {
            jLabel3.setText(String.valueOf(100-z*9));
        }
        if(i >29000 && i<=30000)
        {
            jLabel3.setText(String.valueOf(100-z*10));
        }
        if(i >30000 && i<=31000)
        {
            jLabel3.setText(String.valueOf(100-z*11));
        }
        if(i >31000 && i<=32000)
        {
            jLabel3.setText(String.valueOf(100-z*12));
        }
        if(i >32000 && i<=33000)
        {
            jLabel3.setText(String.valueOf(100-z*13));
        }
        if(i >33000 && i<=34000)
        {
            jLabel3.setText(String.valueOf(100-z*14));
        }
        if(i >34000 && i<=35000)
        {
            jLabel3.setText(String.valueOf(100-z*15));
        }
        if(i >35000 && i<=36000)
        {
            jLabel3.setText(String.valueOf(100-z*16));
        }
        if(i >36000 && i<=40000)
        {
            jLabel3.setText(String.valueOf(100-z*17));
        }
if(i >40000 && i<=45000)
        {
            jLabel3.setText(String.valueOf(100-z*19));
        }
if(i >45000 && i<=50000)
        {
            jLabel3.setText(String.valueOf(100-z*21));
        }
if(i >50000 && i<=55000)
        {
            jLabel3.setText(String.valueOf(100-z*23));
        }
if(i >55000 && i<=60000)
        {
            jLabel3.setText(String.valueOf(100-z*25));
        }
if(i >60000 && i<=65000)
        {
            jLabel3.setText(String.valueOf(100-z*27));
        }
if(i >65000 && i<=70000)
        {
            jLabel3.setText(String.valueOf(100-z*29));
        }
if(i >70000 && i<=75000)
        {
            jLabel3.setText(String.valueOf(100-z*31));
        }
if(i >75000 && i<=80000)
        {
            jLabel3.setText(String.valueOf(100-z*33));
        }
if(i >80000 && i<=85000)
        {
            jLabel3.setText(String.valueOf(100-z*35));
        }
if(i >85000 && i<=90000)
        {
            jLabel3.setText(String.valueOf(100-z*37));
        }
if(i >90000 && i<=95000)
        {
            jLabel3.setText(String.valueOf(100-z*39));
        }
if(i >95000 && i<=100000)
        {
            jLabel3.setText(String.valueOf(100-z*41));
        }
if(i >100000 && i<=150000)
        {
            jLabel3.setText(String.valueOf(100-z*42));
        }
if(i >150000 && i<=200000)
        {
            jLabel3.setText(String.valueOf(100-z*43));
        }
if(i >200000 && i<=250000)
        {
            jLabel3.setText(String.valueOf(100-z*44));
        }
if(i >250000 && i<=300000)
        {
            jLabel3.setText(String.valueOf(100-z*45));
        }
if(i >300000 && i<=350000)
        {
            jLabel3.setText(String.valueOf(100-z*46));
        }
if(i >350000 && i<=400000)
        {
            jLabel3.setText(String.valueOf(100-z*47));
        }
if(i >400000 && i<=450000)
        {
            jLabel3.setText(String.valueOf(100-z*48));
        }
if(i >450000 && i<=500000)
        {
            jLabel3.setText(String.valueOf(100-z*48));
        }
if(i >500000)
        {
            jLabel3.setText(String.valueOf(100-z*50));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String pass,pass1="amanbvp";
        try
        {
            pass=jPasswordField1.getText();
            if(pass.equals(pass1))
            {
                JOptionPane.showMessageDialog(null,"LOGIN OK");
               

                jPasswordField1.setEnabled(false);
                jLabel9.setEnabled(false);
                jLabel8.setEnabled(false);
                jButton7.setEnabled(false);
                jButton5.setEnabled(true);
                jButton4.setEnabled(true);
                jSpinner1.setEnabled(true);
                jTextField2.setEnabled(true);
                jLabel5.setEnabled(true);
                jLabel6.setEnabled(true);
            }
        }
        catch (Exception e)
        {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String s1="C:\\Users\\hp-pc\\Documents\\NetBeansProjects\\google\\src\\google\\newpackage\\", s2=".jpg";
        Integer f=(Integer) jSpinner1.getValue();
        jTextField1.setText(String.valueOf(f));
        String s=s1+jTextField1.getText()+s2;
        jLabel6.setIcon(new ImageIcon(s));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            String url=jTextField2.getText();
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e)
        {

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        jButton11.setEnabled(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int retVal = jFileChooser3.showOpenDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser3.getSelectedFile();
            jLabel13.setIcon(new ImageIcon(""+f));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        String s= (String)(jComboBox1.getSelectedItem());
        if("a".equals(s))
        {
            jLabel14.setText("BANk Sector");
            jButton11.setEnabled(false);

        }

        if("b".equals(s))
        {
            jLabel14.setText("Near PUNE");
            jButton11.setEnabled(false);

        }
        if("c".equals(s))
        {
            jLabel14.setText("Flood River");
            jButton11.setEnabled(false);

        }
        if("d".equals(s))
        {
            jLabel14.setText("Coding Mchine");
            jButton11.setEnabled(false);

        }
        if("e".equals(s))
        {
            jLabel14.setText("Plaute");
            jButton11.setEnabled(false);

        }
        if("f".equals(s))
        {
            jLabel14.setText("Nazi Ship");
            jButton11.setEnabled(false);

        }
        if("g".equals(s))
        {
            jLabel14.setText("A building about 25km from here (in pune)");
            jButton11.setEnabled(false);

        }
        if("h".equals(s))
        {
            jLabel14.setText("3 idiots");
            jButton11.setEnabled(false);

        }
        if("i".equals(s))
        {
            jLabel14.setText("Muahhh...  :*");
            jButton11.setEnabled(false);

        }
        if("j".equals(s))
        {
            jLabel14.setText("World known physicist and philospher");
            jButton11.setEnabled(false);

        }
        if("k".equals(s))
        {
            jLabel14.setText("Casino Capital");
            jButton11.setEnabled(false);

        }
        if("l".equals(s))
        {
            jLabel14.setText(" originally called Harwell ");
            jButton11.setEnabled(false);

        }
        if("m".equals(s))
        {
            jLabel14.setText("Always COOL ");
            jButton11.setEnabled(false);

        }
        if("n".equals(s))
        {
            jLabel14.setText("Most powerfull man in INDIA");
            jButton11.setEnabled(false);

        }
        if("o".equals(s))
        {
            jLabel14.setText("Led ________ ");
            jButton11.setEnabled(false);

        }
        if("p".equals(s))
        {
            jLabel14.setText("Sri-lanka");
            jButton11.setEnabled(false);

        }
        z1=z1-30;
       jLabel15.setText(String.valueOf(z1));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String pass,pass1="bvpcomp";
        try
        {
            pass=jPasswordField2.getText();
            if(pass.equals(pass1))
            {
                JOptionPane.showMessageDialog(null,"LOGIN OK");

                jPasswordField2.setEnabled(false);
                jLabel11.setEnabled(false);
                jLabel12.setEnabled(false);
                jButton9.setEnabled(false);
                jButton8.setEnabled(true);
                jButton6.setEnabled(true);
                jButton10.setEnabled(true);
                jComboBox1.setEnabled(true);
                jLabel7.setEnabled(true);
                jLabel10.setEnabled(true);
                jLabel11.setEnabled(true);
                jButton11.setEnabled(true);
                jButton12.setEnabled(true);
            }
        }
        catch (Exception e)
        {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String s1="C:\\Users\\hp-pc\\Documents\\NetBeansProjects\\google\\src\\google\\newpackage\\", s2=".jpg";
        String s= (String)(jComboBox1.getSelectedItem());
        String s3=s1+s+s2;
        jLabel10.setIcon(new ImageIcon(s3));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try
        {
            String url="https://www.google.co.in/imghp?hl=en&tab=wi&ei=Dwv5Uu8tgdGtB93rgeAJ&ved=0CAQQqi4oAg";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jFileChooser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser3ActionPerformed
        BufferedImage image = null;
        jFileChooser3.setAcceptAllFileFilterUsed(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try
        {
            String url="http://dictionary.reference.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gooooog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gooooog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gooooog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gooooog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gooooog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
